bucket_name         = "prod-us-east-1-georgetonietti-pipeline"
instance_type       = "t3.micro"
ami_id              = "ami-0c02fb55956c7d316"
security_group_name = "prod-securitygroup"
docker_image        = "georgetonietti/helloaws:latest"