bucket_name         = "dev-us-east-1-georgetonietti-pipeline"
instance_type       = "t2.nano"
ami_id              = "ami-0c101f26f147fa7fd"
security_group_name = "dev-securitygroup"
docker_image        = "georgetonietti/helloaws:latest"