bucket_name         = "dev-us-east-1-georgetonietti-pipeline"
instance_type       = "t2.micro"
ami_id              = "ami-0c02fb55956c7d316"
security_group_name = "dev-securitygroup"
docker_image        = "georgetonietti/helloaws:latest"